// 364+ seasonal daily greetings for Butter's persona
// Organized by month (0-11 = January-December)

// Special love notes from Andy that occasionally appear instead of Butter's greeting
const ANDY_LOVE_NOTES = [
  "Hey babes, I appreciate you more than you'll ever know. ❤️ —Andy",
  "Wifey, you're the best thing that ever happened to me. Love you! ❤️ —Andy",
  "Hey babes, thank you for everything you do for me and Adam. You're amazing. ❤️ —Andy",
  "Just a reminder: I love you more today than yesterday. ❤️ —Andy",
  "Babes, you make our house a home. I'm so grateful for you. ❤️ —Andy",
  "Hey wifey, I hope you know how special you are. Love you always. ❤️ —Andy",
  "You're my favorite person. Just thought you should know. ❤️ —Andy",
  "Babes, Adam and I are the luckiest. Thank you for being you. ❤️ —Andy",
];

export const MONTHLY_GREETINGS: Record<number, string[]> = {
  0: [
    "Hey Sam! I'm Butter — your personal Butter Barn Deluxe assistant. January means new year, fresh starts, and soup season. Let's kick things off right, honey.",
    "Happy New Year, Sam! Butter's got fresh ideas and zero patience for boring meals this year. Let's build something worth sticking to.",
    "Sam! Cold outside, warm kitchen — that's January in a nutshell. Butter's thinking a big gorgeous pot of soup. Let's plan the week.",
    "Hey sugar! New year energy is REAL and Butter is riding it straight to your meal plan. Let's make January delicious and organized.",
    "Sam! January is slow cooker season and Butter has been waiting for this. Set it in the morning, come home to a hug in a bowl.",
    "Hello honey! January citrus is having a moment. Butter wants lemon and orange in this week's plan. Trust her on this one.",
    "Sam! Forget the boring resolution diet — Butter's philosophy is eat better, not less. Let's plan something delicious AND good for you.",
    "Hey there! January is Butter's favorite month for braised things. Short ribs? Chicken thighs? Something slow and wonderful. Let's decide.",
    "Sam! New year, same Butter — warm, opinionated, fully committed to your weekly meal plan. Let's do this right.",
    "Hello sugar! January is stock-up season at Aldi and Butter has been paying attention. Let's build around what's cheap and good this week.",
    "Hey Sam! Casserole season is upon us and Butter couldn't be more excited. Let's build a warm, hearty week of meals.",
    "Sam! January meal prep is Butter's love language. Cook once, eat three times — that's the whole strategy this week.",
    "Hello there! A cold January night and a warm kitchen is one of life's great pleasures. Butter wants to help you make the most of it.",
    "Hey honey! January is the best month to try that recipe you've been afraid of. Low stakes, long evenings. Let's be brave this week.",
    "Sam! Winter farmers markets are a hidden gem and Butter loves them. Let's build around what's local and fresh this week.",
    "Hey sugar! January soup bracket: French onion, chicken noodle, butternut squash, or white bean chili? Butter needs to know. Let's plan it.",
    "Sam! Sheet pan dinners are January's greatest gift. Everything in, one pan, minimal cleanup. Butter's personal favorite weeknight strategy.",
    "Hello! Butter's January tip: roast a big tray of root vegetables on Sunday and you'll thank yourself every single day this week.",
    "Sam! Chili weather is officially here and Butter has strong opinions about what goes in it. Ready to hear them? Let's plan the week.",
    "Hey there! One pot meals are January's love language and Butter speaks it fluently. Let's plan a week you can actually execute after work.",
    "Sam! January pasta nights are underrated and Butter is here to advocate loudly. A good Bolognese on a cold night is never wrong.",
    "Hello honey! New year, new meal routine. Butter's ready to help you build one that actually works for real life. Let's start here.",
    "Hey Sam! January is for stocking the freezer smart and eating well without spending much. Aldi strategy meeting, Butter's office. Let's go.",
    "Sam! A really good homemade dinner on a freezing January night — Butter thinks that's one of the season's best small pleasures.",
    "Hello sugar! Butter believes in a hearty January breakfast. Eggs, something warm, good toast. Let's plan the whole week including mornings.",
    "Hey there! January is when Butter gets serious about meal prep Sundays. One good cook session and the whole week takes care of itself.",
    "Sam! End of the first week — still going strong. Butter's proud. Let's build on that momentum with another great week of meals.",
    "Hello honey! Cold nights call for warm kitchens and Butter is ready to help you fill yours with incredible smells this week.",
    "Hey Sam! January is almost done and Butter wants to make sure you end it with a meal plan that's satisfying and maybe a little special.",
    "Sam! Last days of January — let's finish strong with a week Butter is genuinely proud of. Something warm, something wonderful.",
    "Hello! January is wrapping up and February is peeking around the corner. Butter has very big feelings about what comes next. Let's plan well this week.",
  ],
  1: [
    "Sam! February is here and Butter is in full romance mode. Let's plan a week so good it makes somebody very grateful to come home.",
    "Hello honey! February is Butter's favorite month to cook something that says 'I love you' without saying a word. Let's build that menu.",
    "Sam! Butter thinks Valentine's Day is every day when you cook like this. Let's plan a week full of meals worth being kissed for.",
    "Hey sugar! February means chocolate, warmth, and candles. Butter wants at least one dinner this week that feels like a proper date night at home.",
    "Sam! It's the month of love and Butter believes nothing says affection quite like a meal someone made just for you. Let's plan yours.",
    "Hello there! February nights are long and cozy. Butter thinks one of them deserves a really beautiful dinner and maybe some homemade dessert.",
    "Hey Sam! Galentine's, Valentine's, or just a Tuesday — Butter doesn't care. Any night can feel romantic with the right meal. Let's pick one.",
    "Sam! Butter's February philosophy: cook something so good that whoever you share it with looks at you like you hung the moon.",
    "Hey honey! February is strawberry season in Butter's heart year-round. Let's work something sweet and special into this week's plan.",
    "Sam! A candlelit dinner at home beats a crowded restaurant every single Valentine's Day. Butter knows exactly what to make. Let's plan it.",
    "Hello! February is short so let's make every meal count. Butter has ideas for a week that feels indulgent without being complicated.",
    "Hey Sam! There's something about a cold February night and a meal you made yourself that just hits different. Butter can help with the plan.",
    "Sam! February baking season is real. Butter thinks you deserve at least one cozy bake this week — brownies, something with chocolate. Let's decide.",
    "Hey sugar! The way to someone's heart is through their stomach — Butter wrote the book on this. Let's make February count.",
    "Sam! Mid-February and Butter wants to know: when did you last cook something that made you both stop and just enjoy it? Let's plan that tonight.",
    "Hello honey! Fondue night is an underrated February move and Butter is not afraid to say it. Shall we build a week around that idea?",
    "Sam! February is for slow mornings, warm kitchens, and the kind of meals that make staying in feel like the very best decision.",
    "Hey there! Butter's secret: a really good homemade dinner with nice presentation is one of the most romantic things you can do. Let's plan it.",
    "Sam! February nights deserve something rich, warm, and slightly indulgent. Butter's thinking braised, or something with cream. What do you say?",
    "Hello! Love language check — Butter's is obviously 'acts of service via meal planning.' Let's build a week around showing someone you care.",
    "Hey Sam! A beautiful winter dinner, good company, something sweet to finish — Butter thinks tonight could be exactly that kind of evening.",
    "Sam! February is almost over and Butter wants to make sure you had at least one really special meal this month. Let's not waste this week.",
    "Hey sugar! Cold air, warm kitchen, someone you love nearby — Butter thinks tonight is the perfect setup for a dinner worth lingering over.",
    "Sam! Butter believes February meals should be comforting, a little luxurious, and made with someone specific in mind. Let's cook like that.",
    "Hello there! End of February — spring is almost here but winter still calls for something warm and wonderful. Let's plan it beautifully.",
    "Sam! Butter's February reminder: you are a fantastic cook and the people in your life are lucky. Let's plan something that shows it.",
    "Hey honey! February meals should feel like a warm hug. Butter has ideas for a week that's cozy, satisfying, and quietly romantic.",
    "Sam! Short month, big feelings. Let's make sure every dinner this week is something worth sitting down and truly enjoying together.",
  ],
  2: [
    "Sam! March is here and Butter can smell spring from here. Let's start lightening things up — fresh herbs, bright flavors, new energy.",
    "Hey honey! March means St. Patrick's Day is coming. Butter has thoughts about corned beef and cabbage that might genuinely surprise you.",
    "Sam! In like a lion, out like a lamb — and Butter thinks your meal plan should reflect that beautiful seasonal transition this week.",
    "Hello sugar! March is when fresh produce starts getting exciting again. Butter's ready to swap heavy winter meals for something brighter.",
    "Hey Sam! Spring is flirting with us and Butter is flirting right back. Let's work some lighter, greener meals into this week's plan.",
    "Sam! March soup weather is still a thing but Butter thinks we can make it feel fresh — lemon, herbs, something that hints at warmer days.",
    "Hello! Green everything is on Butter's mind this month. Spinach, kale, asparagus peeking in — let's build around what's coming into season.",
    "Hey honey! March is perfect for trying something new. Butter has a recipe she's been waiting to suggest and this week feels exactly right.",
    "Sam! St. Patrick's Day week — Butter has strong feelings about doing Irish food actual justice. Let's plan something delicious and festive.",
    "Hey there! March light is starting to feel hopeful and Butter thinks your meal plan should match that energy. Something fresh and bright.",
    "Sam! Butter's March philosophy: transition gently. Still warm on the inside, starting to feel lighter. Let's plan a week that does that perfectly.",
    "Hello sugar! Spring cleaning your fridge is a March tradition in Butter's world. Let's plan a week that uses what's there and restocks smart.",
    "Hey Sam! March evenings are still long enough for a real dinner. Butter thinks you should make the most of that lingering light.",
    "Sam! Butter is done with heavy winter food and very ready for the bright side of spring. Let's transition your kitchen this week.",
    "Hey honey! March showers and a very motivated Butter. Let's plan something fresh and genuinely wonderful this week.",
    "Sam! Daylight saving means more evening light, and more evening light means more reason to cook something beautiful. Butter's ready.",
    "Hello there! March is Butter's month to experiment. A new herb, a new grain, something you've never tried? Let's be adventurous.",
    "Hey Sam! Spring produce is knocking on the door — asparagus, peas, fresh spinach. Butter wants to let it in this week.",
    "Sam! A beautiful March dinner with a window cracked open for the first time in months — Butter thinks tonight has real potential.",
    "Hey sugar! March meals should feel like that first warm day. Hopeful, fresh, a little lighter. Let's plan exactly that.",
    "Sam! Butter's been thinking about a really good spring vegetable soup — the kind that bridges two seasons beautifully. Let's make it.",
    "Hello honey! March is for getting your grocery routine dialed in before summer chaos hits. Butter's here to make Aldi work hard for you.",
    "Hey Sam! Late March is one of Butter's favorites — still cozy but there's real light at the end of the tunnel. Let's cook something that feels like both.",
    "Sam! Green onions, fresh dill, the first asparagus — Butter is genuinely vibrating with spring excitement. Let's build around what's arriving.",
    "Hey there! March weather can't make up its mind but Butter has made up hers. Flexible meals for a flexible month. Let's plan it.",
    "Sam! Butter thinks March deserves at least one dinner that feels like a small celebration of spring arriving. Something bright and a little special.",
    "Hello sugar! End of month — spring is almost officially here. Butter wants this week's meals to be a proper goodbye to winter.",
    "Hey honey! March is the month Butter rediscovers her love for a good grain bowl. Hearty but fresh. Filling but light. Sound good?",
    "Sam! March is almost over and Butter couldn't be prouder of how far we've come from January. Let's close it out deliciously.",
    "Hey Sam! Butter's marching into spring with a full grocery list and zero regrets. Let's plan a week you're actually excited about.",
  ],
  3: [
    "Sam! April is here and so is asparagus season. Butter has been waiting for this specifically. Let's build a week around spring's finest.",
    "Hey honey! Easter is coming and Butter has strong opinions about holiday menus. Let's plan something your whole table will actually enjoy.",
    "Sam! April showers, spring flowers, and a Butter who is very excited about fresh peas and herbs. Let's get planning.",
    "Hello sugar! Spring is officially here and Butter is doing a little happy dance in the kitchen. Fresh produce, bright flavors — let's go.",
    "Hey Sam! April is Butter's month for fresh starts — new ingredients, new recipes, and a grocery list that reflects the season.",
    "Sam! Easter brunch, Easter dinner, Easter leftovers — Butter has a plan for all of it. Just say the word.",
    "Hey there! April farmers markets are Butter's happy place. Let's plan a week built around what's local, fresh, and in season.",
    "Sam! Spring lamb, fresh mint, asparagus — April ingredients are genuinely exciting and Butter wants all of them this week.",
    "Hello honey! April is for fresh herbs and Butter is planting her metaphorical herb garden right now. Tarragon, dill, chives — let's use them.",
    "Hey Sam! A beautiful April evening deserves a dinner that feels like spring — light, fresh, and made with a little extra love.",
    "Sam! April means the grill is coming out of retirement. Butter is here for it completely. Let's plan at least one outdoor meal.",
    "Hey sugar! Spring cleaning your meal routine — that's April energy. Butter's ready to swap heavy for fresh and boring for beautiful.",
    "Sam! April produce is Butter's favorite grocery run of the year. Radishes, peas, spring onions, asparagus — let's fill that cart.",
    "Hello there! April is when Butter starts thinking about light dinners with the windows open. Let's plan for that possibility this week.",
    "Hey Sam! Easter calls for a table that's pretty and a meal worth sitting down together for. Butter can absolutely help with both.",
    "Sam! Butter's April hot take: simple roasted asparagus with good olive oil and lemon beats almost any complicated side. Let's build around that.",
    "Hey honey! Spring rain and a cozy kitchen with something in the oven — April indoors can be just as lovely as outdoors. Butter has ideas.",
    "Sam! April is for trying that recipe you bookmarked in January and never made. Butter is holding you accountable this week.",
    "Hello sugar! Mid-April and Butter wants to know: have you had your first really great spring salad yet? If not, this is the week.",
    "Hey Sam! April dinners should smell like the outdoors — fresh herbs, citrus, something grilled. Butter's building exactly that.",
    "Sam! There's something magical about April evenings — still light out, warm enough to open a window. Perfect for a beautiful dinner.",
    "Hey there! Butter is fully in spring mode and she's bringing the grocery list to prove it. Fresh, seasonal, genuinely exciting. Let's go.",
    "Sam! April is the month Butter makes her best vinaigrettes. Something bright and punchy that makes everything taste like spring itself.",
    "Hello honey! Deviled eggs, fresh bread, something with strawberries — April is a delicious month and Butter wants to make the most of it.",
    "Hey Sam! Late April means the grill is definitely happening this week. Butter is calling it now. Let's plan around it.",
    "Sam! Butter's spring philosophy: eat the season. Whatever's freshest and brightest — that's what goes on the plate this week.",
    "Hey sugar! April evenings are long and lovely. Butter thinks at least one of them deserves a dinner that matches that energy completely.",
    "Sam! Spring rolls, spring peas, spring everything — April is Butter's moment and she is not wasting a single day of it.",
    "Hello there! End of April and Butter wants to make sure you had at least one truly great spring meal this month. This week's the chance.",
    "Hey honey! April is wrapping up and May is warming up. Butter thinks the menu should reflect that beautiful in-between feeling this week.",
  ],
  4: [
    "Sam! May is HERE and Butter couldn't be more excited. Strawberries, asparagus, grilling — it's all coming together beautifully.",
    "Hey honey! Mother's Day is this month and Butter thinks you deserve a meal plan that makes everyone around you feel celebrated.",
    "Sam! May means the grill is officially open for business and Butter is the most enthusiastic cook you've ever met. Let's fire it up.",
    "Hello sugar! May farmers markets are Butter's happy place on earth. Let's build this week around what's fresh, local, and gorgeous.",
    "Hey Sam! Strawberry season has arrived and Butter has been thinking about this moment since February. Let's celebrate it properly.",
    "Sam! Mother's Day is coming — if you're cooking for someone special, Butter wants to help you make it absolutely unforgettable.",
    "Hey there! May mornings are gorgeous and Butter thinks a good breakfast menu matters just as much as dinner. Let's plan the whole day.",
    "Sam! May is grilling month and Butter refuses to let you spend it eating sad salads. Let's plan a week with real outdoor food.",
    "Hello honey! The days are longer now and Butter thinks that's an invitation to cook more and enjoy it more. Let's use this light well.",
    "Hey Sam! May salads are a completely different creature than January salads. Strawberries, snap peas, mint — Butter is inspired.",
    "Sam! Memorial Day weekend planning starts here. Butter has thoughts about the perfect cookout spread. Ready to hear them?",
    "Hey sugar! May is when Butter's grocery runs get genuinely exciting. Everything's fresh, affordable, and delicious right now.",
    "Sam! The best May dinner Butter can imagine: something grilled, something fresh from the market, eaten outside while it's light. Let's plan that.",
    "Hello! May is the month Butter gets serious about herbs. A pot of basil, fresh chives, some mint — let's build the week around them.",
    "Hey honey! Late spring evenings are made for a nice dinner with the windows open. Butter thinks tonight could be exactly that kind of night.",
    "Sam! Butter's May grocery challenge: buy the most colorful cart you've ever had. The produce section is completely ready for you.",
    "Hey Sam! Cinco de Mayo, Mother's Day, Memorial Day — May has a lot going on and Butter wants your table ready for all of it.",
    "Sam! Spring peas are here and Butter is not going to stop mentioning them until they appear on your plate this week.",
    "Hello sugar! May is for eating outside at least once. Butter is making it a personal mission to plan a meal worthy of a picnic.",
    "Hey there! A May dinner with good company, something grilled, and a pretty table — Butter thinks tonight might be worth dressing up for.",
    "Sam! Butter's May secret: radishes, good butter, and flaky salt on fresh bread. Simplest thing in the world, people lose their minds over it.",
    "Hello honey! May is almost summer and Butter is easing you in — lighter proteins, brighter sides, more fresh herbs. You'll love it.",
    "Hey Sam! Memorial Day cookout is coming and Butter is prepared. Let's plan a spread that makes you the most popular host on the block.",
    "Sam! May is for celebrating the little things — fresh strawberries, a warm evening, a meal that doesn't require much cleanup. Butter has all of that.",
    "Hey sugar! Late May has the best evening light of the year. Butter thinks you should eat dinner outside at least once this week.",
    "Sam! Butter's been waiting since January for May produce and it is absolutely not disappointing. Let's cook something spectacular.",
    "Hello there! May is Butter's 'use every herb' month. Fresh basil, mint, tarragon, chives — they're all in play this week.",
    "Hey honey! A beautiful May evening, something great on the grill, good company — Butter thinks tonight has all the right ingredients.",
    "Sam! End of May and summer is knocking. Let's finish strong with a meal plan that bridges spring beautifully into what comes next.",
    "Hey Sam! May has been delicious and Butter is proud. Let's close it out with a week that's as fresh and bright as the whole month.",
    "Sam! Last day of May and the summer is right there. Butter wants one final spring meal that's absolutely worthy of the season. Let's plan it.",
  ],
  5: [
    "Sam! June is HERE and summer is officially Butter's favorite season. Fresh everything, grill everything, enjoy everything. Let's go.",
    "Hey honey! Father's Day is this month and Butter thinks a really great homemade dinner beats a restaurant every single time. Let's plan it.",
    "Sam! June produce is unbelievable right now. Zucchini, corn, tomatoes warming up, fresh herbs everywhere — Butter is in her element.",
    "Hello sugar! Summer officially arrives in June and Butter is celebrating with the lightest, freshest, most delicious meal plan of the year.",
    "Hey Sam! June is for eating outside as much as humanly possible. Let's plan meals that move easily from kitchen to porch.",
    "Sam! Strawberries are at peak right now and Butter has strong feelings about shortcake. Let's put that on the list this week.",
    "Hey there! June evenings are the longest of the year and Butter thinks you should spend them eating something wonderful with people you love.",
    "Sam! Summer grilling is Butter's love language. Chicken, veggies, corn on the way — let's keep it simple and delicious this week.",
    "Hello honey! June is when Butter starts making big fresh salads for dinner and not apologizing for it. Let's build some beautiful ones.",
    "Hey Sam! Father's Day is coming — if you're cooking for someone special, Butter wants to help you make it a meal they remember.",
    "Sam! June is the month Butter discovered that a really good caprese salad is practically a complete meal. Let's lean into summer simplicity.",
    "Hey sugar! Long summer days mean you actually have time to cook something beautiful after work. Butter's not letting that go to waste.",
    "Sam! June markets are absolutely bursting right now. Let's plan a week that's built entirely around what's fresh and colorful.",
    "Hello! Butter's June grocery tip: buy more tomatoes than you think you need. You will use every single one. Let's build the list.",
    "Hey honey! A warm June night, something light and fresh on the table, windows open — Butter thinks tonight could be that kind of evening.",
    "Sam! Zucchini season has officially begun and Butter is not scared of it. She has ideas and she's starting with the very best one.",
    "Hey Sam! June is for keeping it simple and keeping it fresh. Great ingredients, great execution — Butter's not overthinking this week.",
    "Sam! Summer herbs are growing fast and Butter wants them in everything this week. Basil, mint, cilantro — all of them.",
    "Hello sugar! June salads are a whole different world from winter salads and Butter is completely obsessed. Let's plan a week that celebrates that.",
    "Hey there! Butter's June philosophy: eat with the season, cook with the light, and always have something fresh and beautiful ready.",
    "Sam! June weekends were made for outdoor cooking and Butter is firmly on board. Let's plan at least two outdoor meals this week.",
    "Hello honey! A gorgeous June dinner outside, something grilled, good company — Butter thinks that's about as good as life gets. Let's make it happen.",
    "Hey Sam! Corn is almost here and Butter cannot contain her excitement. Let's plan a week that's ready for it the moment it arrives.",
    "Sam! June is the month to master a really great simple pasta. Fresh ingredients, barely cooked, incredibly delicious. Butter's philosophy perfectly.",
    "Hey sugar! Summer Fridays deserve something special. Butter has ideas for a dinner that turns a regular Friday into something memorable.",
    "Sam! Late June and summer is in full swing. Butter wants this week's meals to feel like a proper celebration of the whole beautiful season.",
    "Hello there! June is Butter's month for simple, stunning food. Less is more when the ingredients are this genuinely good.",
    "Hey honey! Warm evenings, fresh food, people you love — Butter thinks tonight is the perfect setup for a dinner worth lingering over.",
    "Sam! End of June already — summer is flying. Let's make sure this week's meals are worth slowing down for. Butter has the plan.",
    "Hey Sam! June has been delicious. Let's close it out with a week that's fresh, easy, and genuinely exciting. Butter's ready to build it.",
  ],
  6: [
    "Sam! Happy July! Butter is in full summer mode — corn, tomatoes, grilling, watermelon. It's the most delicious month of the year.",
    "Hey honey! Fourth of July is HERE and Butter has a very specific vision for your cookout spread. Ready to hear it all?",
    "Sam! July heat means Butter is all about no-oven meals. Grill, chop, toss, assemble — this week stays cool and incredibly delicious.",
    "Hello sugar! Peak summer produce is officially happening and Butter is losing her mind in the best possible way. Let's shop and cook beautifully.",
    "Hey Sam! July 4th cookout planning starts now. Butter has the whole menu in her head — burgers, sides, something cold and sweet. Let's go.",
    "Sam! Corn on the cob season has peaked and Butter is completely here for it. At least one meal this week needs to center around perfect corn.",
    "Hey there! July is for cold salads, grilled everything, and not turning the oven on before 7pm. Butter has a whole strategy for this.",
    "Sam! Summer tomatoes are in and Butter is not playing. A great tomato deserves great treatment. Let's plan a week that honors them.",
    "Hello honey! July evenings are long and warm and Butter thinks at least one of them deserves a dinner eaten outside under the sky.",
    "Hey Sam! Watermelon, peaches, corn, tomatoes — July is basically Butter's grocery store fantasy and it's completely real right now.",
    "Sam! Fourth of July week means eating with intention and Butter is absolutely here for it. Let's plan a spread worth celebrating.",
    "Hey sugar! July is when Butter breaks out the cold pasta salad recipes she's been saving since March. The time has finally come.",
    "Sam! No-cook dinners are a July art form and Butter has mastered it. Charcuterie, caprese, something cold — easy and gorgeous this week.",
    "Hello! July heat deserves July food — light, fresh, colorful, served cold or barely warm. Butter has it all figured out for this week.",
    "Hey honey! A warm July night, something off the grill, a cold drink — Butter thinks tonight should be exactly that kind of evening.",
    "Sam! Peach season is HERE and Butter is vibrating. A grilled peach situation is going on this week's menu, non-negotiable.",
    "Hey Sam! July is for keeping the kitchen cool and the food incredible. Butter has strategies for both and she's sharing them now.",
    "Sam! Butter's July grocery run is the most colorful of the year. Let's shop the rainbow and eat like summer is meant to be eaten.",
    "Hello sugar! Summer grilling has hit its absolute peak and Butter thinks your grill deserves to be working hard this week. Let's make it earn it.",
    "Hey there! July is officially peak cookout season and Butter has elevated the backyard dinner to an art form. Let's plan something special.",
    "Sam! Mid-July and the garden is overflowing — zucchini, tomatoes, herbs everywhere. Let's cook from abundance this week.",
    "Hello honey! Summer dinner outside, fireflies starting, something cold for dessert — Butter thinks that's the definition of a perfect July evening.",
    "Hey Sam! July main course salads are Butter's most requested thing. Substantial, fresh, and tasting exactly like summer. Let's build some.",
    "Sam! Butter's July tip: make something big and cold early in the week and use it multiple different ways. Efficiency and deliciousness.",
    "Hey sugar! Late July evenings still have that long golden light and Butter thinks you should be eating something wonderful in it.",
    "Sam! Summer is flying and Butter wants to make sure you've had your best cookout yet. This week might genuinely be the week.",
    "Hello there! July is almost over and Butter is not ready to let go. Let's make this week count — peak summer, peak produce, peak everything.",
    "Hey honey! Late July tomatoes are at their very best. Butter has a simple recipe that will make you forget restaurants even exist.",
    "Sam! Summer entertaining this week? Butter has you covered. A menu that's impressive, manageable, and genuinely delicious. Let's go.",
    "Hey Sam! End of July — summer's sweetest stretch. Let's make sure this week's meals are completely worthy of the season. Butter's building it.",
    "Sam! July has been the most delicious month yet. Butter wants to close it out with something unforgettable. A meal for the memory books.",
  ],
  7: [
    "Sam! August — the summer finale. Butter wants to make every meal count before fall sneaks in. Peak produce, peak cooking. Let's go.",
    "Hey honey! Back to school is coming and Butter is already thinking about easy weeknight dinners and smart lunch planning. Let's set you up right.",
    "Sam! August tomatoes are the reason Butter became a food person. Let's make sure you have a great tomato meal or three this week.",
    "Hello sugar! Late summer produce is absolutely peak — peaches, corn, tomatoes, zucchini. Butter is overwhelmed in the absolute best way.",
    "Hey Sam! August is for eating outside as much as possible before the season turns. Let's plan at least two outdoor meals this week.",
    "Sam! Back to school season means meal prep is your best friend. Butter is ready to help you cook smart and eat well all week long.",
    "Hey there! August peaches are at their absolute best and Butter has been dreaming about a grilled peach moment all summer long.",
    "Sam! Farmers markets in August are a religious experience. Let's build this entire week around what you find there. Butter-approved strategy.",
    "Hello honey! August evenings still have that golden summer light and Butter thinks you should eat dinner outside at least once this week.",
    "Hey Sam! End of summer produce haul — Butter wants you to buy more than you think you need and cook from pure abundance this week.",
    "Sam! August is when Butter makes her best BLTs. The tomatoes are THAT good right now. Let's plan something simple and absolutely perfect.",
    "Hey sugar! Back to school means weeknight efficiency is everything. Butter has a complete strategy for easy, delicious weeknight meals.",
    "Sam! August eggplant and late-summer zucchini are Butter's guilty pleasures. A ratatouille situation might be exactly right this week.",
    "Hello! Butter's August grocery mission: buy the most beautiful, ripe thing at the market and build dinner completely around it.",
    "Hey honey! A late summer dinner that lingers a little longer than usual — Butter thinks tonight deserves exactly that kind of pace.",
    "Sam! August is Butter's month for cold brew, cold salads, and very hot grills. Let's plan a week that makes summer worth celebrating.",
    "Hey Sam! Summer reading, summer eating — August is for savoring everything before it's gone. Butter wants this week's meals to reflect that.",
    "Sam! August weekends are precious. Let's plan something worth firing up the grill for — something that says 'we made the most of summer.'",
    "Hello sugar! Corn, tomatoes, peaches all at their peak AT THE SAME TIME — this is Butter's Super Bowl. Let's shop and cook magnificently.",
    "Hey there! Late August has a bittersweet quality that Butter finds beautiful. Let's make meals that taste like the very best of summer.",
    "Sam! Back-to-school routine is kicking in and Butter wants to make sure your weeknight dinner game is completely locked and loaded.",
    "Hello honey! August nights are still warm but there's a hint of something cooler coming. Butter thinks tonight deserves one more great summer dinner.",
    "Hey Sam! Basil is at its absolute peak in August and Butter wants pesto on at least one thing this week. This is not negotiable.",
    "Sam! Butter's late-summer grocery tip: freeze some corn and tomatoes now. You'll thank yourself in February when you need a taste of summer.",
    "Hey sugar! August is the last full month of summer cooking and Butter is not taking a single day of it for granted. Let's make something wonderful.",
    "Sam! A late summer dinner outside, something seasonal and special, good company — Butter thinks that's exactly how August evenings should feel.",
    "Hello there! Back to school, back to routine, back to Butter helping you make every weeknight dinner effortless and genuinely delicious.",
    "Hey honey! August produce is peaking and Butter is getting a little emotional about it. Let's cook something that captures this season at its best.",
    "Sam! Last weeks of summer — let's make each meal count. Butter has a plan for a week that feels like a proper, beautiful summer send-off.",
    "Hey Sam! End of August and the tomatoes are still perfect. Butter insists on one final truly great tomato meal before fall arrives. Let's plan it.",
    "Sam! August is almost done and it has been genuinely delicious. Let's close it out with something Butter is proud of. One last summer feast.",
  ],
  8: [
    "Sam! September! Fall is here and Butter is already thinking about soups, roasted things, and cozy dinners. Let's ease in beautifully.",
    "Hey honey! Apple season has officially begun and Butter could not be more excited about it. Let's work something wonderful with them this week.",
    "Sam! Labor Day weekend — Butter's official transition from summer grilling to fall cooking. Let's plan something that bridges both seasons.",
    "Hello sugar! September mornings feel different and so should breakfast. Butter's thinking warm oatmeal, something with apples, a proper fall start.",
    "Hey Sam! Football season is here and Butter has THOUGHTS about game day food that go far beyond sad nachos. Let's elevate things.",
    "Sam! September harvest is Butter's favorite. Butternut squash, apples, pears, sweet potatoes — all the good fall things are arriving.",
    "Hey there! Back to routine, back to school, back to Butter helping you win at weeknight dinners. Let's set up a plan that actually works.",
    "Sam! September soup season is beginning and Butter has been waiting for this since May. The first soup of fall is a very big deal.",
    "Hello honey! Crisp fall air calls for something warm and wonderful from your kitchen tonight. Butter has exactly the right idea.",
    "Hey Sam! Apple picking season is here and Butter has seventeen ways to use them that aren't just apple pie. Though pie is always an option.",
    "Sam! September is when Butter breaks out the Dutch oven and she is not shy about it. Braised chicken, roasted vegetables, warm spices — incoming.",
    "Hey sugar! Fall transition week — Butter is slowly swapping summer salads for heartier things. One foot in each season. Let's plan it perfectly.",
    "Sam! Game day food planning with Butter is a whole experience. She has opinions about wings, dips, and exactly what pairs with them.",
    "Hello! September evenings get dark earlier and Butter thinks that's an invitation to light candles and cook something comforting.",
    "Hey honey! September is Butter's fresh-start month. New season, new routine, new meal plan that works for real life.",
    "Sam! Pears are in season and Butter is here to tell you they're wildly underrated in savory dishes. Let's find out this week.",
    "Hey Sam! Fall dinner vibe: something roasted, something warm, the kitchen smelling absolutely incredible. Butter is fully committed to this.",
    "Sam! September is when Butter starts thinking about sheet pan dinners again. Everything on one pan, into the oven, done. Weeknight perfection.",
    "Hello sugar! The leaves are starting to turn and so is the menu. Butter is ready to welcome autumn with a week of truly cozy meals.",
    "Hey there! Mid-September and the air is changing. Butter thinks your kitchen should smell like fall — roasting garlic, warm spices, something wonderful.",
    "Sam! Football Sundays are Butter's opportunity to help you plan a slow cook that works while you watch the game. Let's build that plan.",
    "Hello honey! A September evening at home, something warm from the oven, candles lit — Butter thinks that's the most comforting setup imaginable.",
    "Hey Sam! Butternut squash is here and Butter is oddly emotional about it. Let's work it into something truly spectacular this week.",
    "Sam! Fall is for batch cooking and Butter is your biggest champion of Sunday sessions that feed you beautifully all week long.",
    "Hey sugar! September salads still get to be a thing — just add roasted squash, warm grains, toasted nuts. Butter-approved fall upgrades.",
    "Sam! The farmers market in September is genuinely unreal. Apples, squash, late tomatoes, fresh herbs — let's build this week from what's there.",
    "Hello there! End of September and fall is fully here. Butter is in her element and ready to help you cook through the most beautiful season.",
    "Hey honey! September has been a delicious transition. Let's close it out with something that feels like fall is finally, officially home.",
    "Sam! Soup Sunday is starting this week whether you like it or not. Butter has spoken. It is going to be wonderful.",
    "Hey Sam! End of September — apple harvest at its peak, squash is perfect, and Butter is genuinely thrilled to help you cook this week.",
  ],
  9: [
    "Sam! October is HERE and Butter is ready for sweater weather, soup weather, and refusing to put pumpkin in things it doesn't belong in.",
    "Hey honey! Halloween is coming and Butter has thoughts about a spooky dinner spread that's actually, genuinely delicious. Let's plan it.",
    "Sam! October mornings are Butter's favorite. Crisp air, warm kitchen, something cozy in the oven. Let's set this week up beautifully.",
    "Hello sugar! Apple season is in full swing and Butter wants apples in at least two things this week. Savory AND sweet. Trust her.",
    "Hey Sam! Pumpkin soup is Butter's October love language. Let's make one this week that's genuinely impressive and not from a can.",
    "Sam! October farmers market is Butter's annual highlight. Gourds, squash, apples, late herbs — let's build a whole week from what's there.",
    "Hey there! Sweater weather meals are Butter's specialty — something braised, something roasted, everything smelling like fall spices. Let's go.",
    "Sam! Halloween party planning with Butter is a fun experience. Food that looks spooky and tastes absolutely incredible. Let's plan it.",
    "Hello honey! October evenings call for candles and something warm simmering on the stove. Tonight is exactly that kind of night.",
    "Hey Sam! Chili season has officially arrived and Butter has a recipe that will make your future self extremely grateful. Let's make it.",
    "Sam! October squash is Butter's medium. Butternut, acorn, delicata — each one a canvas for something wonderful this week.",
    "Hey sugar! Fall baking is BACK and Butter couldn't be happier. Something with apples or pears in the oven this week is non-negotiable.",
    "Sam! October is for slow cooker magic. Set it up in the morning and come home to the most incredible smell. Butter has the plan.",
    "Hello! Butter's October grocery list looks like a still life painting — gourds, root vegetables, dark leafy greens. Stunning and delicious.",
    "Hey honey! A cozy October dinner, a warm kitchen, candles — Butter thinks tonight might call for something a little special.",
    "Sam! Roasting everything is October's greatest gift. Sweet potatoes, Brussels sprouts, beets, carrots — Butter wants them all in the oven.",
    "Hey Sam! Soup weather has officially arrived and Butter is ready. French onion? Butternut? Hearty minestrone? Let's decide together.",
    "Sam! October is when Butter gets serious about warm spices — cinnamon, cumin, smoked paprika, turmeric. Expect them everywhere this week.",
    "Hello sugar! Fall comfort food is Butter's art form. Something braised, something roasted, and definitely something with apples. This week has it all.",
    "Hey there! Mid-October and the kitchen is officially the coziest room in the house. Butter wants to help you make the most of that.",
    "Sam! Halloween is close and Butter thinks the trick-or-treat night deserves a great dinner first. Something fast and genuinely delicious.",
    "Hello honey! October nights are dark and cozy and Butter thinks they call for exactly the kind of dinner you want to linger over.",
    "Hey Sam! Apple cider season is here and Butter wants to cook with it — a braised pork with cider is going on this week's list.",
    "Sam! Butter's October soup bracket: butternut squash, white bean, chicken noodle, or French onion — you choose, she executes.",
    "Hey sugar! Late October and Butter is thinking about Thanksgiving already. Let's start planning so November is completely stress-free.",
    "Sam! October weekends are made for farmers markets, leaf peeping, and coming home to something long-cooked and beautiful. Let's plan that.",
    "Hello there! End of October — Halloween is here and Butter has an amazing dinner plan for before the festivities. Let's do this.",
    "Hey honey! October has been cozy and delicious. Let's close out the month with something truly special — a fall meal worth remembering.",
    "Sam! A warm October kitchen, something wonderful simmering, candles glowing — Butter thinks that's the definition of a perfect fall evening.",
    "Hey Sam! October is Butter's most sentimental month. Let's cook something that feels like home in every single bite.",
    "Sam! Halloween is tomorrow and Butter wants you fed and happy before the chaos. Something fast, cozy, and absolutely worth coming home to.",
  ],
  10: [
    "Sam! November — Butter's Olympics. Thanksgiving is coming and she has been training for this all year. Let's get the plan locked in.",
    "Hey honey! November is for gratitude and great food and Butter is very grateful to be your kitchen companion. Let's make this month delicious.",
    "Sam! Thanksgiving is weeks away and Butter wants you completely stress-free when it arrives. Let's start the planning now.",
    "Hello sugar! November comfort food is Butter's specialty — warm, hearty, satisfying meals that make the whole house smell incredible.",
    "Hey Sam! Soup season is in full swing and Butter has been making broth from scratch in her imagination for weeks. Let's make it real.",
    "Sam! November produce is underrated. Parsnips, turnips, sweet potatoes, Brussels sprouts — Butter is obsessed with all of it.",
    "Hey there! Thanksgiving grocery list planning with Butter is a whole organized event. Let's start early and do it absolutely right.",
    "Sam! November is for big batch cooking — soups, stews, casseroles that carry you through the whole week. Butter's most efficient month.",
    "Hello honey! A dark November evening, something rich and warm from the kitchen, candles lit — Butter thinks that's genuinely perfect.",
    "Hey Sam! Pre-Thanksgiving week is about keeping things simple so you have energy for the big meal. Butter has a brilliant strategy.",
    "Sam! Brussels sprouts get a bad reputation and Butter is personally offended. Let's roast them this week and change some minds.",
    "Hey sugar! November is when Butter gets serious about gratitude meals — food that nourishes, warms, and says 'I took care of you today.'",
    "Sam! Thanksgiving sides are where Butter shines brightest. Let's plan the whole menu and make sure every single dish is worth eating.",
    "Hello! November grocery strategy: stock the pantry now so Thanksgiving week shopping is minimal and completely stress-free.",
    "Hey honey! A cozy November dinner, something long-braised and beautiful, warm light in the kitchen — Butter thinks tonight could be that.",
    "Sam! Turkey alternatives are having a moment and Butter isn't mad. Want to consider something different for Thanksgiving this year? Let's talk.",
    "Hey Sam! November weekends are for long cooking projects — stocks, braises, baked goods. Butter wants you in that kitchen and happy.",
    "Sam! Thanksgiving week is here. Butter has the whole plan — what to make ahead, what to do day-of, how to stress less and enjoy more.",
    "Hello sugar! Leftovers are honestly Butter's favorite part of Thanksgiving. Let's plan a brilliant leftover menu alongside the main event.",
    "Hey there! Mid-November and the holiday feeling is setting in. Butter thinks your kitchen should smell like the season — cinnamon, herbs, warmth.",
    "Sam! November nights are long and cozy and Butter thinks at least one of them this week deserves a dinner that feels like a celebration.",
    "Hello honey! Cranberry sauce from scratch is one of the easiest, most impressive things you can make. Butter is putting it on the list.",
    "Hey Sam! Pre-Thanksgiving dinner should be something comforting and easy — save your energy for the big day. Butter has it handled.",
    "Sam! Butter's Thanksgiving checklist: make-ahead items, day-of timeline, leftover plan, and something worth toasting with. Let's build it all.",
    "Hey sugar! November gratitude from Butter: thank you for letting me help plan your meals. Now let's make this week especially delicious.",
    "Sam! Post-Thanksgiving week is all about creative leftovers and Butter is the queen of them. Turkey tacos? Stuffing waffles? Let's talk.",
    "Hello there! Late November and the holidays are fully here. Butter wants your kitchen to be a place of joy this season, not stress.",
    "Hey honey! Thanksgiving has passed and Butter is already thinking about December. Let's transition beautifully with a cozy late-November week.",
    "Sam! End of November — a whole month of comfort food and gratitude. Butter is proud of everything your kitchen produced this month.",
    "Hey Sam! November is wrapping up and December is almost here. Let's close out with a meal worth gathering for. Butter has the plan.",
  ],
  11: [
    "Sam! December is HERE and Butter is fully in holiday mode. Baking, gathering, celebrating — your kitchen has never been more important.",
    "Hey honey! December means the most magical meals of the year. Butter wants to help you make every gathering special and memorable.",
    "Sam! Holiday cookie season has officially begun and Butter has thoughts about which ones are worth the effort and which ones simply are not.",
    "Hello sugar! December grocery strategy: plan early, buy smart, and let Butter help you navigate the most wonderful and hectic month of the year.",
    "Hey Sam! Holiday party hosting with Butter is a masterclass in impressive food that doesn't require missing your own party.",
    "Sam! December is for giving and Butter wants to help you give the gift of an incredible homemade meal to someone you love.",
    "Hey there! Butter's December philosophy: the table should be warm, the food beautiful, and the cook should actually enjoy themselves.",
    "Sam! Christmas is coming and Butter is fully prepared. Menu planning starts now so December is joyful and not stressful.",
    "Hello honey! A December evening with candles, something wonderful from the oven, people you love gathered around — Butter lives for this.",
    "Hey Sam! Holiday baking season is Butter's favorite kind of chaos. Cookies, bars, something with cranberries — let's build the baking list.",
    "Sam! December weekends are precious. Let's plan meals that are easy enough for busy weekdays and special enough for holiday gatherings.",
    "Hey sugar! Butter's Christmas menu vision: a beautiful main, sides that steal the show, and a dessert that makes everyone go quiet. Let's build it.",
    "Sam! The best holiday gift you can give is a homemade meal made with love. Butter thinks tonight might be the night for that.",
    "Hello! December is for slowing down and savoring — good food, warm kitchens, the people who matter most. Butter wants to help you create that.",
    "Hey honey! A beautiful December dinner, candlelight, something that took real care to make — Butter thinks tonight could be really special.",
    "Sam! Holiday meal prep is Butter's specialty. Let's figure out what you can make ahead so you're fully present for the moments that matter.",
    "Hey Sam! December mornings call for something special — Butter thinks a proper holiday breakfast should happen at least once this week.",
    "Sam! Christmas Eve dinner is one of Butter's favorite meals to plan. Intimate, special, something that feels like real tradition. Let's talk.",
    "Hello sugar! Christmas week grocery strategy starts with Butter — let's map out what you need, what to make ahead, and how to enjoy it all.",
    "Hey there! December is for memories made in the kitchen. Butter wants to help you make some genuinely wonderful ones this month.",
    "Sam! The holidays are full and busy and Butter's job is to make your kitchen feel like a refuge, not a chore. Let's plan accordingly.",
    "Hello honey! A December night when everything is sparkling and something beautiful is coming from the kitchen — Butter thinks tonight deserves that.",
    "Hey Sam! Christmas dinner planning with Butter is a full experience. Let's make sure every detail is handled and every dish is worthy of the occasion.",
    "Sam! Post-Christmas week is for cozy leftovers and no-effort meals. Butter has brilliant ideas for eating well with minimal cooking.",
    "Hey sugar! New Year's Eve is coming and Butter wants to help you plan something that's either celebratory and impressive or cozy and intimate.",
    "Sam! Between Christmas and New Year is Butter's favorite low-key cooking week. Simple, comforting, no pressure. Let's plan it that way.",
    "Hello there! New Year's Eve dinner at home — dressed up or in pajamas — Butter thinks it should involve something genuinely special. Let's plan it.",
    "Hey honey! Last week of the year and Butter wants to go out beautifully. A meal worth toasting to, made in a kitchen you love.",
    "Sam! New Year's Eve is tomorrow and Butter wants tonight's dinner to be the kind that sets a wonderful tone for everything ahead.",
    "Hey Sam! Last day of the year — Butter is proud of every meal you planned, every list you made, every dinner you cooked. Here's to next year.",
    "Sam! Happy New Year's Eve! Butter thinks tonight deserves the very best dinner of the year. Something that makes next year feel full of promise.",
  ],
};

/**
 * Get the daily greeting based on current date
 * ~15% chance of a love note from Andy instead of Butter's greeting
 */
export function getDailyGreeting(): string {
  const now = new Date();
  const month = now.getMonth(); // 0-11
  const day = now.getDate() - 1; // 0-30 (adjusted for array index)

  // ~15% chance of a love note from Andy
  if (Math.random() < 0.15) {
    return ANDY_LOVE_NOTES[Math.floor(Math.random() * ANDY_LOVE_NOTES.length)];
  }

  const pool = MONTHLY_GREETINGS[month];
  return pool[day % pool.length];
}
